export enum SideList {
	Frontend = 'frontend',
	Backend = 'backend',
	Tools = 'tools',
	Other = 'other',
}

export enum SideListMap {
	frontend,
	backend,
	tools,
	other,
}

export const Sides: Record<SideList, { label: string; class: string }[]> = {
	[SideList.Frontend]: [
		{ label: 'Vue 3', class: 'vue' },
		{ label: 'Vue 2', class: 'vue' },
		{ label: 'Vuelidate', class: 'vuelidate' },
		{ label: 'Vuetify', class: 'vuetify' },
		{ label: 'Luxon', class: 'luxon' },
		{ label: 'Lodash', class: 'lodash' },
		{ label: 'GSAP', class: 'gsap' },
		{ label: 'CASL', class: 'casl' },
		{ label: 'Pinia', class: 'pinia' },
		{ label: 'SCSS', class: 'scss' },
		{ label: 'JSX', class: 'jsx' },
		{ label: 'TSX', class: 'tsx' },
		{ label: 'JavaScript', class: 'js' },
		{ label: 'TypeScript', class: 'ts' },
		{ label: 'HTML 5', class: 'html' },
		{ label: 'CSS', class: 'css' },
	],
	[SideList.Backend]: [
		{ label: 'Node.js', class: 'nodejs' },
		{ label: 'Express.js', class: 'expressjs' },
		{ label: 'SQL', class: 'sql' },
		{ label: 'PostgreSQL', class: 'postgresql' },
		{ label: 'MongoDB', class: 'mongodb' },
		{ label: 'MySQL', class: 'mysql' },
		{ label: 'Redis', class: 'redis' },
		{ label: 'Sequlize', class: 'sequelize' },
		{ label: 'API', class: 'api' },
		{ label: 'REST API', class: 'restapi' },
		{ label: 'Web sockets', class: 'websocket' },
	],
	[SideList.Tools]: [
		{ label: 'Webpack', class: 'webpack' },
		{ label: 'Vite', class: 'vite' },
		{ label: 'Git', class: 'git' },
		{ label: 'Github', class: 'github' },
		{ label: 'Gitlab', class: 'gitlab' },
		{ label: 'Docker', class: 'docker' },
		{ label: 'K8S', class: 'kuber' },
		{ label: 'VDS', class: 'vds' },
		{ label: 'VPS', class: 'vps' },
		{ label: 'Figma', class: 'figma' },
		{ label: 'Agile (Scrum)', class: 'agile' },
		{ label: 'БЭМ', class: 'bem' },
		{ label: 'CI/CD', class: 'cicd' },
		{ label: 'SSDLC', class: 'ssdlc' },
		{ label: 'MPA', class: 'mpa' },
		{ label: 'SPA', class: 'spa' },
		{ label: 'SSR', class: 'ssr' },
		{ label: 'NGINX', class: 'nginx' },
	],
	[SideList.Other]: [
		{ label: 'Passwork', class: 'passwork' },
		{ label: 'Harbor', class: 'harbor' },
		{ label: 'Vault', class: 'vault' },
		{ label: 'Zabbix', class: 'zabbix' },
		{ label: '1С', class: 'ones' },
		{ label: 'Netbox', class: 'netbox' },
		{ label: 'VictoriaMetrics', class: 'victoriametrics' },
	],
};